// GENERATED by scripts/generate-catalog-structures.ts — do not hand-edit.
// Placeholder until the first generation run; empty means every entry has no
// structure yet (veto and category signals stay silent — fails safe).
import type { DishStructure } from './dishStructure';

export const STRUCTURES: Record<string, DishStructure> = {};
