// Chinese (HK) names for key ingredients — extracted from DishInfoDisplay.tsx so
// every place an ingredient gets rendered (dish-info chips, the growth screen's
// absorb-effect words) shares ONE glossary. Two independent translation tables for
// the same fixed English vocabulary (menuScan.ts's "i" field is always English,
// lowercase — no zh counterpart is stored on the dish) would drift and disagree.
// Specific/compound keys come FIRST so they win the substring match (e.g. "chinese
// broccoli" → 芥蘭 before generic "broccoli" → 西蘭花). Falls back to null
// (caller decides the English fallback) when unmatched — never a fabricated zh name.
const INGREDIENT_ZH: { keys: string[]; zh: string }[] = [
  { keys: ['chinese broccoli', 'kai lan', 'kailan', 'gai lan', 'kalian'], zh: '芥蘭' },
  { keys: ['bok choy', 'pak choi'], zh: '白菜' },
  { keys: ['napa', 'chinese cabbage'], zh: '大白菜' },
  { keys: ['green bean', 'string bean', 'french bean'], zh: '四季豆' },
  { keys: ['edamame'], zh: '毛豆' },
  { keys: ['bell pepper', 'capsicum'], zh: '燈籠椒' },
  { keys: ['green onion', 'spring onion', 'scallion'], zh: '蔥' },
  { keys: ['mock fish', 'vegetarian fish', 'veggie fish'], zh: '齋魚' },
  { keys: ['shiitake'], zh: '冬菇' },
  { keys: ['enoki'], zh: '金菇' },
  { keys: ['oyster mushroom'], zh: '蠔菇' },
  { keys: ['porcini'], zh: '牛肝菌' },
  { keys: ['mushroom'], zh: '蘑菇' },
  { keys: ['garlic'], zh: '蒜' },
  { keys: ['ginger'], zh: '薑' },
  { keys: ['chili', 'chilli', 'chile'], zh: '辣椒' },
  { keys: ['shallot'], zh: '乾蔥' },
  { keys: ['leek'], zh: '大蔥' },
  { keys: ['onion'], zh: '洋蔥' },
  { keys: ['tomato'], zh: '番茄' },
  { keys: ['egg'], zh: '蛋' },
  { keys: ['carrot'], zh: '甘筍' },
  { keys: ['potato'], zh: '薯仔' },
  { keys: ['corn'], zh: '粟米' },
  { keys: ['eggplant', 'aubergine'], zh: '茄子' },
  { keys: ['broccoli'], zh: '西蘭花' },
  { keys: ['cucumber'], zh: '青瓜' },
  { keys: ['lettuce'], zh: '生菜' },
  { keys: ['spinach'], zh: '菠菜' },
  { keys: ['kale'], zh: '羽衣甘藍' },
  { keys: ['cabbage'], zh: '椰菜' },
  { keys: ['choy', 'greens'], zh: '青菜' },
  { keys: ['lemon'], zh: '檸檬' },
  { keys: ['lime'], zh: '青檸' },
  { keys: ['avocado'], zh: '牛油果' },
  { keys: ['coconut'], zh: '椰子' },
  { keys: ['pineapple'], zh: '菠蘿' },
  { keys: ['mango'], zh: '芒果' },
  { keys: ['apple'], zh: '蘋果' },
  { keys: ['banana'], zh: '香蕉' },
  { keys: ['grape'], zh: '提子' },
  { keys: ['strawberr'], zh: '士多啤梨' },
  { keys: ['peach'], zh: '桃' },
  { keys: ['cherr'], zh: '車厘子' },
  { keys: ['olive'], zh: '橄欖' },
  { keys: ['peanut'], zh: '花生' },
  { keys: ['cashew'], zh: '腰果' },
  { keys: ['almond'], zh: '杏仁' },
  { keys: ['walnut'], zh: '合桃' },
  { keys: ['nut'], zh: '果仁' },
  { keys: ['bean'], zh: '豆' },
  { keys: ['cheese'], zh: '芝士' },
  { keys: ['butter'], zh: '牛油' },
  { keys: ['bread', 'bun', 'toast'], zh: '麵包' },
  { keys: ['rice'], zh: '飯' },
  { keys: ['ramen'], zh: '拉麵' },
  { keys: ['udon'], zh: '烏冬' },
  { keys: ['pasta', 'spaghetti'], zh: '意粉' },
  { keys: ['noodle'], zh: '麵' },
  { keys: ['shrimp', 'prawn'], zh: '蝦' },
  { keys: ['crab'], zh: '蟹' },
  { keys: ['lobster'], zh: '龍蝦' },
  { keys: ['squid', 'calamari'], zh: '魷魚' },
  { keys: ['octopus'], zh: '八爪魚' },
  { keys: ['salmon'], zh: '三文魚' },
  { keys: ['tuna'], zh: '吞拿魚' },
  { keys: ['cod'], zh: '鱈魚' },
  { keys: ['fish'], zh: '魚' },
  { keys: ['bacon'], zh: '煙肉' },
  { keys: ['chicken'], zh: '雞' },
  { keys: ['beef', 'steak'], zh: '牛肉' },
  { keys: ['pork'], zh: '豬肉' },
  { keys: ['duck'], zh: '鴨' },
  { keys: ['lamb', 'mutton'], zh: '羊' },
  { keys: ['honey'], zh: '蜜糖' },
  { keys: ['cream'], zh: '忌廉' },
  { keys: ['milk'], zh: '奶' },
  { keys: ['chocolate', 'cocoa'], zh: '朱古力' },
  { keys: ['basil'], zh: '羅勒' },
  { keys: ['mint'], zh: '薄荷' },
  { keys: ['cilantro', 'coriander'], zh: '芫茜' },
  { keys: ['parsley'], zh: '番茜' },
  { keys: ['lemongrass'], zh: '香茅' },
  { keys: ['herb'], zh: '香草' },
];

export function ingredientZh(raw: string): string | null {
  const s = raw.toLowerCase();
  for (const { keys, zh } of INGREDIENT_ZH) {
    if (keys.some(k => s.includes(k))) return zh;
  }
  return null;
}
