/**
 * Regenerates src/lib/hkDishCatalogStructures.gen.ts — the structural
 * decomposition of every catalog entry's own zh name.
 *
 * OFFLINE ON PURPOSE: the catalog is fixed, so its structures are data, not
 * runtime work. Checking them in makes the category derivation (empty
 * ingredient slot -> not a merge target) and every veto input REVIEWABLE in a
 * diff — a miscategorised entry is caught by a human reading the output, not
 * discovered as a production false-merge. Review the printed CATEGORY list
 * before committing; in particular, drinks and plain dishes (港式奶茶, 白粥)
 * must come out `absent`, never `unspecified`, or a real entry silently stops
 * being a merge target.
 *
 * RUN (after any catalog edit):
 *   set -a; source .env.local; set +a
 *   npx tsx scripts/generate-catalog-structures.ts
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { CATALOG } from '../src/lib/hkDishCatalog';
import { decomposeDishNames } from '../src/lib/dishCanonical';
import { isCategoryStructure } from '../src/lib/dishStructure';

(async () => {
  console.log(`Decomposing ${CATALOG.length} catalog entries (batch=2, reasoning model — this takes a few minutes)…`);
  const structures = await decomposeDishNames(CATALOG.map(e => e.zh));

  const missing = CATALOG.filter((_, i) => !structures.has(i));
  if (missing.length) {
    console.warn(`\n⚠ ${missing.length} entries failed to decompose (they'll have no structure — veto and category stay silent for them):`);
    missing.forEach(e => console.warn(`   ${e.id} (${e.zh})`));
  }

  const lines = CATALOG.map((e, i) => {
    const s = structures.get(i);
    if (!s) return null;
    return `  '${e.id}': { protein: '${s.protein}', method: '${s.method}', base: '${s.base}', parseable: ${s.parseable} }, // ${e.zh}`;
  }).filter(Boolean);

  const out = `// GENERATED by scripts/generate-catalog-structures.ts — do not hand-edit.
// Structural decomposition of each catalog entry's own zh name, checked in so
// the category derivation and veto inputs are reviewable in a diff.
// Regenerate after any catalog change. Generated ${new Date().toISOString().slice(0, 10)}.
import type { DishStructure } from './dishStructure';

export const STRUCTURES: Record<string, DishStructure> = {
${lines.join('\n')}
};
`;

  const path = join(__dirname, '../src/lib/hkDishCatalogStructures.gen.ts');
  writeFileSync(path, out);
  console.log(`\nWrote ${lines.length}/${CATALOG.length} structures to ${path}`);

  const categories = CATALOG.filter((e, i) => {
    const s = structures.get(i);
    return s && isCategoryStructure(s);
  });
  console.log(`\n── CATEGORY entries (empty ingredient slot — will NOT be merge targets) ──`);
  categories.forEach(e => console.log(`   ${e.id}  (${e.zh} / ${e.en})`));
  console.log(`\nReview that list. Expected members: fried-rice-generic, double-boiled-soup.`);
  console.log(`If milk-tea or another specific dish appears there, the decomposition is wrong — fix guidance and re-run.`);
})();
